import { Dropdown, Form, FormSelectProps } from "react-bootstrap";
import { useTranslation } from "react-i18next";
import { forwardRef, useState } from "react";

import useStore from "../../../common/zustand/Store";
import { ConfigurationType } from "../../../common/zustand/interface/ConfigurationInterface";

import useActiveConfiguration from "../../../common/hooks/ActiveConfiguration";

import EditConfiguration from "./modals/EditConfiguration";

type ApiConfigurationDropdownToggleProps = {
    selectedValue?: string;
};

// Apply select input as the custom dropdown toggle for Api Configuration Dropdown
const ApiConfigurationDropdownToggle = forwardRef<
    HTMLSelectElement,
    FormSelectProps & ApiConfigurationDropdownToggleProps
>((props, ref) => {
    const { t } = useTranslation();

    const configuration = useStore((state) =>
        state.configuration.filter((c) => c.type === ConfigurationType.API)
    );

    return (
        <Form.Select
            className="text-rg px-12 py-6 text-dark-gray rounded-6 border-platinum"
            ref={ref}
            aria-label="auth-dropdown"
            /* We need to prevent dropdown options generated by the browser from appearing. */
            onMouseDown={(e) => {
                e.preventDefault();
            }}
            onClick={(e) => {
                e.preventDefault();
                props.onClick?.(e);
            }}
            value={props.selectedValue || ""}
            onChange={() => {
                // noop
            }}
        >
            {/* Placeholder for the dropdown */}
            <option hidden>{t("api.dashboard.header.dropdown.select")}</option>

            {configuration.map(({ name, uuid }) => (
                <option hidden value={uuid} key={uuid}>
                    {name}
                </option>
            ))}
        </Form.Select>
    );
});

const ApiConfigurationDropdown = () => {
    const { t } = useTranslation();

    const [showEditModal, setShowEditModal] = useState(false);

    const { configuration, setSelectedConfiguration } = useStore((state) => ({
        // Get the list of API configuration only
        configuration: state.configuration.filter(
            (c) => c.type === ConfigurationType.API
        ),
        setSelectedConfiguration: state.setSelectedConfiguration,
    }));

    const activeConfiguration = useActiveConfiguration(ConfigurationType.API);

    const selectableConfiguration = configuration.filter(
        (config) => config.uuid !== activeConfiguration?.uuid
    );

    return (
        <>
            <Dropdown className="w-100">
                <Dropdown.Toggle
                    as={ApiConfigurationDropdownToggle}
                    selectedValue={activeConfiguration?.uuid}
                />

                <Dropdown.Menu className="text-rg w-100">
                    <Dropdown.Item onClick={() => setShowEditModal(true)}>
                        {t("api.dashboard.header.dropdown.edit")}
                    </Dropdown.Item>

                    {activeConfiguration && (
                        <Dropdown.Item
                            onClick={() => setSelectedConfiguration()}
                        >
                            {t("api.dashboard.header.dropdown.clear")}
                        </Dropdown.Item>
                    )}

                    {/* Ensure divider line is not shown when there's no configuration */}
                    {selectableConfiguration.length > 0 && (
                        <Dropdown.Divider className="mx-2 bg-light-gray" />
                    )}

                    {/* Only show configurations that are not active */}
                    {selectableConfiguration.map(({ uuid, name }) => (
                        <Dropdown.Item
                            key={uuid}
                            onClick={() => setSelectedConfiguration(uuid)}
                            className="text-truncate"
                        >
                            {name}
                        </Dropdown.Item>
                    ))}
                </Dropdown.Menu>
            </Dropdown>

            {/* Edit Configuration Modal */}
            <EditConfiguration
                show={showEditModal}
                handleClose={() => setShowEditModal(false)}
            />
        </>
    );
};

export default ApiConfigurationDropdown;
